/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppCollectionsRouteImport } from './routes/app.collections'
import { Route as AppComponentsRouteImport } from './routes/app.components'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppDatasheetsRouteImport } from './routes/app.datasheets'
import { Route as AppDeveloperRouteImport } from './routes/app.developer'
import { Route as AppEvidenceRouteImport } from './routes/app.evidence'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppMonitorRouteImport } from './routes/app.monitor'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSymbolStudioRouteImport } from './routes/app.symbol-studio'
import { Route as AppSymbolsRouteImport } from './routes/app.symbols'
import { Route as AppUploadRouteImport } from './routes/app.upload'
import { Route as AppComponentsMpnRouteImport } from './routes/app.components.$mpn'
import { Route as AppDatasheetsDatasheetIdRouteImport } from './routes/app.datasheets.$datasheetId'
import { Route as AppEvidenceEvidenceIdRouteImport } from './routes/app.evidence.$evidenceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppComponentsRoute = AppComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasheetsRoute = AppDatasheetsRouteImport.update({
  id: '/datasheets',
  path: '/datasheets',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperRoute = AppDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorRoute = AppMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSymbolStudioRoute = AppSymbolStudioRouteImport.update({
  id: '/symbol-studio',
  path: '/symbol-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppSymbolsRoute = AppSymbolsRouteImport.update({
  id: '/symbols',
  path: '/symbols',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppComponentsMpnRoute = AppComponentsMpnRouteImport.update({
  id: '/$mpn',
  path: '/$mpn',
  getParentRoute: () => AppComponentsRoute,
} as any)
const AppDatasheetsDatasheetIdRoute =
  AppDatasheetsDatasheetIdRouteImport.update({
    id: '/$datasheetId',
    path: '/$datasheetId',
    getParentRoute: () => AppDatasheetsRoute,
  } as any)
const AppEvidenceEvidenceIdRoute = AppEvidenceEvidenceIdRouteImport.update({
  id: '/$evidenceId',
  path: '/$evidenceId',
  getParentRoute: () => AppEvidenceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/collections': typeof AppCollectionsRoute
  '/app/components': typeof AppComponentsRouteWithChildren
  '/app/copilot': typeof AppCopilotRoute
  '/app/datasheets': typeof AppDatasheetsRouteWithChildren
  '/app/developer': typeof AppDeveloperRoute
  '/app/evidence': typeof AppEvidenceRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/history': typeof AppHistoryRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/monitor': typeof AppMonitorRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/symbol-studio': typeof AppSymbolStudioRoute
  '/app/symbols': typeof AppSymbolsRoute
  '/app/upload': typeof AppUploadRoute
  '/app/': typeof AppIndexRoute
  '/app/components/$mpn': typeof AppComponentsMpnRoute
  '/app/datasheets/$datasheetId': typeof AppDatasheetsDatasheetIdRoute
  '/app/evidence/$evidenceId': typeof AppEvidenceEvidenceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/collections': typeof AppCollectionsRoute
  '/app/components': typeof AppComponentsRouteWithChildren
  '/app/copilot': typeof AppCopilotRoute
  '/app/datasheets': typeof AppDatasheetsRouteWithChildren
  '/app/developer': typeof AppDeveloperRoute
  '/app/evidence': typeof AppEvidenceRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/history': typeof AppHistoryRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/monitor': typeof AppMonitorRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/symbol-studio': typeof AppSymbolStudioRoute
  '/app/symbols': typeof AppSymbolsRoute
  '/app/upload': typeof AppUploadRoute
  '/app': typeof AppIndexRoute
  '/app/components/$mpn': typeof AppComponentsMpnRoute
  '/app/datasheets/$datasheetId': typeof AppDatasheetsDatasheetIdRoute
  '/app/evidence/$evidenceId': typeof AppEvidenceEvidenceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/collections': typeof AppCollectionsRoute
  '/app/components': typeof AppComponentsRouteWithChildren
  '/app/copilot': typeof AppCopilotRoute
  '/app/datasheets': typeof AppDatasheetsRouteWithChildren
  '/app/developer': typeof AppDeveloperRoute
  '/app/evidence': typeof AppEvidenceRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/history': typeof AppHistoryRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/monitor': typeof AppMonitorRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/symbol-studio': typeof AppSymbolStudioRoute
  '/app/symbols': typeof AppSymbolsRoute
  '/app/upload': typeof AppUploadRoute
  '/app/': typeof AppIndexRoute
  '/app/components/$mpn': typeof AppComponentsMpnRoute
  '/app/datasheets/$datasheetId': typeof AppDatasheetsDatasheetIdRoute
  '/app/evidence/$evidenceId': typeof AppEvidenceEvidenceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/signup'
    | '/app/analytics'
    | '/app/collections'
    | '/app/components'
    | '/app/copilot'
    | '/app/datasheets'
    | '/app/developer'
    | '/app/evidence'
    | '/app/help'
    | '/app/history'
    | '/app/jobs'
    | '/app/monitor'
    | '/app/search'
    | '/app/settings'
    | '/app/symbol-studio'
    | '/app/symbols'
    | '/app/upload'
    | '/app/'
    | '/app/components/$mpn'
    | '/app/datasheets/$datasheetId'
    | '/app/evidence/$evidenceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/signup'
    | '/app/analytics'
    | '/app/collections'
    | '/app/components'
    | '/app/copilot'
    | '/app/datasheets'
    | '/app/developer'
    | '/app/evidence'
    | '/app/help'
    | '/app/history'
    | '/app/jobs'
    | '/app/monitor'
    | '/app/search'
    | '/app/settings'
    | '/app/symbol-studio'
    | '/app/symbols'
    | '/app/upload'
    | '/app'
    | '/app/components/$mpn'
    | '/app/datasheets/$datasheetId'
    | '/app/evidence/$evidenceId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/signup'
    | '/app/analytics'
    | '/app/collections'
    | '/app/components'
    | '/app/copilot'
    | '/app/datasheets'
    | '/app/developer'
    | '/app/evidence'
    | '/app/help'
    | '/app/history'
    | '/app/jobs'
    | '/app/monitor'
    | '/app/search'
    | '/app/settings'
    | '/app/symbol-studio'
    | '/app/symbols'
    | '/app/upload'
    | '/app/'
    | '/app/components/$mpn'
    | '/app/datasheets/$datasheetId'
    | '/app/evidence/$evidenceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collections': {
      id: '/app/collections'
      path: '/collections'
      fullPath: '/app/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/components': {
      id: '/app/components'
      path: '/components'
      fullPath: '/app/components'
      preLoaderRoute: typeof AppComponentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/datasheets': {
      id: '/app/datasheets'
      path: '/datasheets'
      fullPath: '/app/datasheets'
      preLoaderRoute: typeof AppDatasheetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/developer': {
      id: '/app/developer'
      path: '/developer'
      fullPath: '/app/developer'
      preLoaderRoute: typeof AppDeveloperRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence': {
      id: '/app/evidence'
      path: '/evidence'
      fullPath: '/app/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitor': {
      id: '/app/monitor'
      path: '/monitor'
      fullPath: '/app/monitor'
      preLoaderRoute: typeof AppMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/symbol-studio': {
      id: '/app/symbol-studio'
      path: '/symbol-studio'
      fullPath: '/app/symbol-studio'
      preLoaderRoute: typeof AppSymbolStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/symbols': {
      id: '/app/symbols'
      path: '/symbols'
      fullPath: '/app/symbols'
      preLoaderRoute: typeof AppSymbolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/components/$mpn': {
      id: '/app/components/$mpn'
      path: '/$mpn'
      fullPath: '/app/components/$mpn'
      preLoaderRoute: typeof AppComponentsMpnRouteImport
      parentRoute: typeof AppComponentsRoute
    }
    '/app/datasheets/$datasheetId': {
      id: '/app/datasheets/$datasheetId'
      path: '/$datasheetId'
      fullPath: '/app/datasheets/$datasheetId'
      preLoaderRoute: typeof AppDatasheetsDatasheetIdRouteImport
      parentRoute: typeof AppDatasheetsRoute
    }
    '/app/evidence/$evidenceId': {
      id: '/app/evidence/$evidenceId'
      path: '/$evidenceId'
      fullPath: '/app/evidence/$evidenceId'
      preLoaderRoute: typeof AppEvidenceEvidenceIdRouteImport
      parentRoute: typeof AppEvidenceRoute
    }
  }
}

interface AppComponentsRouteChildren {
  AppComponentsMpnRoute: typeof AppComponentsMpnRoute
}

const AppComponentsRouteChildren: AppComponentsRouteChildren = {
  AppComponentsMpnRoute: AppComponentsMpnRoute,
}

const AppComponentsRouteWithChildren = AppComponentsRoute._addFileChildren(
  AppComponentsRouteChildren,
)

interface AppDatasheetsRouteChildren {
  AppDatasheetsDatasheetIdRoute: typeof AppDatasheetsDatasheetIdRoute
}

const AppDatasheetsRouteChildren: AppDatasheetsRouteChildren = {
  AppDatasheetsDatasheetIdRoute: AppDatasheetsDatasheetIdRoute,
}

const AppDatasheetsRouteWithChildren = AppDatasheetsRoute._addFileChildren(
  AppDatasheetsRouteChildren,
)

interface AppEvidenceRouteChildren {
  AppEvidenceEvidenceIdRoute: typeof AppEvidenceEvidenceIdRoute
}

const AppEvidenceRouteChildren: AppEvidenceRouteChildren = {
  AppEvidenceEvidenceIdRoute: AppEvidenceEvidenceIdRoute,
}

const AppEvidenceRouteWithChildren = AppEvidenceRoute._addFileChildren(
  AppEvidenceRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppComponentsRoute: typeof AppComponentsRouteWithChildren
  AppCopilotRoute: typeof AppCopilotRoute
  AppDatasheetsRoute: typeof AppDatasheetsRouteWithChildren
  AppDeveloperRoute: typeof AppDeveloperRoute
  AppEvidenceRoute: typeof AppEvidenceRouteWithChildren
  AppHelpRoute: typeof AppHelpRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppJobsRoute: typeof AppJobsRoute
  AppMonitorRoute: typeof AppMonitorRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSymbolStudioRoute: typeof AppSymbolStudioRoute
  AppSymbolsRoute: typeof AppSymbolsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCollectionsRoute: AppCollectionsRoute,
  AppComponentsRoute: AppComponentsRouteWithChildren,
  AppCopilotRoute: AppCopilotRoute,
  AppDatasheetsRoute: AppDatasheetsRouteWithChildren,
  AppDeveloperRoute: AppDeveloperRoute,
  AppEvidenceRoute: AppEvidenceRouteWithChildren,
  AppHelpRoute: AppHelpRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppJobsRoute: AppJobsRoute,
  AppMonitorRoute: AppMonitorRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSymbolStudioRoute: AppSymbolStudioRoute,
  AppSymbolsRoute: AppSymbolsRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
